import Head from 'next/head'
import Layout from '../components/Layout'
import profile from '/public/frontphoto.png' // Updated import path
import Image from 'next/image'
import AnimatedText from '../components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '../components/Icons'
import HireMe from '../components/HireMe'
import lightBuld from "/public/miscellaneous_icons_1.svg" // Updated import path
import TransitionEffect from '../components/TransitionEffect'

export default function Home() {
  return (
    <>
      <Head>
        <title>Yuvraj's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 md:w-full'>
              <Image 
                src={profile} 
                alt="Yuvraj" 
                className='w-full h-auto lg:hidden md:inline-block md:w-full'
                width={500} 
                height={500}
              />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText 
                text="Transforming ideas into reality with passion, precision, and expertise." 
                className='!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl md:mb-2'
              />
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
                As a skilled Electronics as well as software Engineer, I am dedicated to turning ideas into innovative web applications. 
                Explore my latest projects and articles, showcasing my expertise in cyber, DSA, React.js and web development.
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link 
                  href="/WebCV.pdf" 
                  target="_blank" 
                  className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 
                  md:p-2 md:px-4 md:text-base border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light'
                  download={true}
                >
                  Resume
                  <LinkArrow className="w-6 ml-1" />
                </Link>
                <Link 
                  href="https://www.linkedin.com/in/yuvrajsingh001"
                  target="_blank"
                  rel="noopener noreferrer"
                  className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base'
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className='absolute right-8 bottom-8 inline-block w-24 md:hidden'>
          <Image 
            src={lightBuld} 
            alt="Yuvraj Singh" 
            className='w-full h-auto'
            width={96} // Added width (24 * 4 for pixel conversion)
            height={96} // Added height
          />
        </div>
      </main>
    </>
  )
}